### ISSUE TITLE
🌟 Roadmap

### ISSUE THREAD

**Issue by realamirhe** [cnrl/CoNeX#57]
- Conex Gui https://github.com/cnrl/CoNeX/issues/37
- Documentation https://github.com/cnrl/CoNeX/issues/55
- Tutorials https://github.com/cnrl/CoNeX/issues/56

**Comment by realamirhe** [comment]
### `feat` https://github.com/cnrl/CoNeX/issues/59
- [ ] Decision making module `feat`
- [ ] New synapse functions (e.g. AMPA) `feat`
- [ ] Implement `no-self-connection` for synapses `feat`
- [ ] Enhance typing (type-hints) for the conex main core `feat`
- [ ] PyNN integration `feat` 

### `doc` https://github.com/cnrl/CoNeX/issues/55
- [ ] Dependency graph for builtin behaviors `doc`

### `ui` https://github.com/cnrl/CoNeX/issues/37
- [ ] Save the generated components in local storage `ui`
- [ ] Auto load saved component with search feature `ui`
- [ ] Improve customization drawer for containers `ui`

### `test` https://github.com/cnrl/CoNeX/issues/58
- [ ] Add unit-test for behaviors `test`
- [ ] Performance comparison `test`

### `tut` https://github.com/cnrl/CoNeX/issues/56
- [ ] Implement Examples for individual behaviors `tut`
